# Generated by Django 3.1.3 on 2020-11-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='preco',
            field=models.IntegerField(),
        ),
    ]
